//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 TL.rc 使用
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_TL_FORM                     101
#define IDR_MAINFRAME                   128
#define IDR_TLTYPE                      130
#define IDI_ICON_RED                    134
#define IDI_ICON_GRAY                   135
#define IDI_ICON_GREEN                  136
#define ID_ADMIN                        137
#define ID_USER                         138
#define IDD_DIALOG1                     310
#define IDD_LOGIN                       310
#define IDI_ICON3                       312
#define IDD_MAINFORM                    314
#define IDI_ICON1                       314
#define IDD_DIALOG2                     315
#define ID_USER_CHANGE                  315
#define IDD_USER_CHANGE                 315
#define IDC_PRODUCT_INPUT               1002
#define IDC_RADIO_USER                  1002
#define IDC_RADIO_ADMIN                 1003
#define IDC_LOGIN                       1004
#define IDC_SETUP_ACCESS_PASSWORD5      1007
#define IDC_SETUP_ACCESS_PASSWORD6      1008
#define IDC_RICHEDIT                    1009
#define IDC_SETUP_ACCESS_PASSWORD7      1009
#define IDC_EDIT4                       1010
#define IDC_SETUP_ACCESS_PASSWORD8      1010
#define IDC_EDIT_CHECKID                1011
#define IDC_CHECK_REBOOT                1012
#define IDC_STATIC_OLDPWD               1013
#define IDC_STATIC_NEWPWD               1014
#define IDC_STATIC_NEWPWDAG             1015
#define IDC_EDIT_OLDPWD                 1016
#define IDC_EDIT_NEWPWD                 1017
#define IDC_EDIT_NEWPWDAG               1018
#define IDC_PARA_VALUE3                 1019
#define IDC_PARA_VALUE2                 1022
#define IDC_PROG_PROGRESS               1023
#define IDC_PARA_VALUE4                 1023
#define IDC_PARA_VALUE5                 1024
#define IDC_PARA_VALUE6                 1025
#define IDC_PARA_VALUE7                 1026
#define IDC_PARA_VALUE8                 1027
#define IDC_PARA_VALUE9                 1028
#define IDC_PARA_VALUE10                1029
#define IDC_SETUP_CAN_CHAN              1031
#define IDC_APPLICATION_FILE            1033
#define IDC_APPLICATION_BROWSE          1034
#define IDC_SETUP_CAN_TRAID             1035
#define IDC_APPLICATION_IMPORT          1035
#define IDC_SETUP_CAN_RECID             1036
#define IDC_SETUP_CAN_HARDWARE          1059
#define IDC_BUTTON_DOWNLOAD             1066
#define IDC_BAUD_250K                   1068
#define IDC_BAUD_500K                   1069
#define IDC_BAUD_1M                     1070
#define IDC_COMBO1                      1102
#define IDC_COMBO_PRODUCT_TYPE          1102
#define IDC_ORDER_1                     1103
#define IDC_ORDER_CHECK_1               1104
#define IDC_INPUT_PWD                   1104
#define IDC_PRODUCT_TYPE_INPUT          1105
#define IDC_ORDER_3                     1108
#define IDC_USERNAME                    1109
#define IDC_ORDER_2                     1110
#define IDC_ORDER_CHECK_2               1111
#define IDC_PASSWORD                    1112
#define IDC_ORDER_4                     1113
#define IDC_INPUT_USER                  1114
#define IDC_ORDER_CHECK_3               1115
#define IDC_ORDER_5                     1116
#define IDC_ORDER_CHECK_4               1117
#define IDC_PRODUCT_ID                  1118
#define IDC_PARA_VALUE1                 1118
#define IDC_PRODUCT_TYPE                1119
#define IDC_PARA_NAME1                  1119
#define IDC_ORDER_6                     1120
#define IDC_PARA_NAME2                  1120
#define IDC_ORDER_CHECK_5               1121
#define IDC_PARA_NAME3                  1121
#define IDC_ORDER_7                     1122
#define IDC_PARA_NAME4                  1122
#define IDC_ORDER_CHECK_6               1123
#define IDC_PARA_NAME5                  1123
#define IDC_ORDER_8                     1124
#define IDC_PARA_NAME6                  1124
#define IDC_ORDER_CHECK_7               1125
#define IDC_PARA_NAME7                  1125
#define IDC_ORDER_9                     1126
#define IDC_PARA_NAME8                  1126
#define IDC_ORDER_CHECK_8               1127
#define IDC_PARA_NAME9                  1127
#define IDC_ORDER_10                    1128
#define IDC_PARA_NAME10                 1128
#define IDC_ORDER_CHECK_9               1129
#define IDC_ORDER_11                    1130
#define IDC_ORDER_CHECK_10              1131
#define IDD_PROGCANCEL                  1545
#define IDD_PROGRESS                    1545
#define IDD_SETUP                       1546
#define IDD_CONFIG                      1546
#define IDD_BOOTCANCEL                  1547
#define ID_CONFIG_SETUP                 32771
#define ID_Menu                         32771

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        316
#define _APS_NEXT_COMMAND_VALUE         32772
#define _APS_NEXT_CONTROL_VALUE         1017
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
